yungga123/vinculum

application/config/config.php, application/config/routes.php, application/controllers/RequisitionFormController.php, application/models/RequisitionFormModel.php, application/views/requisition_form/requisition_form.php, application/views/requisition_form/script.php
=> REQUISITION FORM DONE

application/controllers/RequisitionFormController.php, application/views/requisition_form/requisition_list.php, application/views/requisition_form/script.php
ADDED DELETE AND REMOVED REQUIRED FIELD IN SUPPLIER AND UNIT COST
=> REVISED REQUISITION FORM

application/controllers/SalesQuotationController.php, application/models/SalesQuotationModel.php
1. Quotation Order_By
2. Quotation Search bar
3. display of sales name
=> Sales Quotation Data Table

application/models/SalesQuotationModel.php
1. Search bar for sales name(last name,first name, middle name)
=> Search Bar

application/views/requisition_form/requisition_form.php
FILTERED PROCESSED BY, APPROVED BY, CHECKED BY
=> UPDATE REQ. FORM

application/controllers/RequisitionFormController.php, application/models/RequisitionFormModel.php, application/views/requisition_form/requisition_form.php, application/views/requisition_form/requisition_list.php, application/views/requisition_form/requisition_view.php, application/views/requisition_form/script.php
added unit field
added unit in view
added unit in print
NOTE: add unit after qty in req_form_item table in database
=> REQ FORM ADJUSTMENT

application/views/dashboard/dashboard.php, application/views/templates/navbar.php
=> Change view in dashboard

application/config/routes.php, application/controllers/RequisitionFormController.php, application/helpers/site_helper.php, application/models/CountsModel.php, application/views/requisition_form/script.php, application/views/templates/navbar.php
added discard feature and discard tables
=> Requisition UPDATE

application/config/routes.php, application/controllers/VendorController.php, application/models/VendorModel.php, application/views/vendor/script.php, application/views/vendor/vendor_add.php, application/views/vendor/vendor_datatable.php, application/views/vendor/vendor_edit.php
1. Vendor Add Form(from modal)
2. Vendor/Brand Additional Details
3. Vendor Datatable Additional Details to  display
=> Vendor Updates-062321-DONE

application/controllers/VendorController.php, application/views/vendor/vendor_edit.php
1. Vendor Solutions to Product
=> Vendor Update

application/controllers/VendorController.php, application/models/VendorModel.php
=> Vendor Database Updates

application/controllers/VendorController.php, application/models/VendorModel.php
=> Vendor Updates

application/views/payroll/payroll_print.php
1. Restday data Displayed to Print
=> Payrol Updates 26/06/21

application/controllers/ItemsController.php, application/models/ItemsModel.php, application/views/items/items_masterlist/items_masterlist.php, application/views/items/items_masterlist/new_item.php, application/views/items/items_masterlist/script.php
1. Brand Column Added
2. Item Description Label Edited
3. Orignal Price Label to Suppler Price Edited
4. SRP Formula
5. Project Price Column Added
6. Project Price Formula
7. Column Size Added
=> Items List Updates

application/config/routes.php, application/controllers/SalesInquiryController.php, application/models/SalesInquiryModel.php, application/views/sales_inquiry/existing_client_view.php, application/views/sales_inquiry/new_client_view.php, application/views/sales_inquiry/project_view.php, application/views/sales_inquiry/script.php
1. Excel Report Per Project of Clients
2. Remarks & Date Column
=> Sales Inquiry Updates

application/views/sales_inquiry/project_view.php
1. set of Checkbox unchehcked generated to add form
=> Sales Inquiry

application/config/config.php, application/controllers/VendorController.php, application/views/vendor/script.php, application/views/vendor/vendor_datatable.php
1. Vendor Code white spaces issue - Solved
2. Brand List View, from solutions to products column - DONE
3. Brand List View products display error - Solved
=> Vendor-Updates:071221

application/controllers/DashboardController.php, application/models/JobOrderModel.php, application/views/dashboard/dashboard.php
1. Replace filed job orders field to for phone support total Count - DONE
=> Dashboard Updates: 072421

application/controllers/VendorController.php, application/models/VendorModel.php, application/views/vendor/vendor_datatable.php, application/views/vendor/vendor_edit.php
1. Update of Vendor Code Validation
=> Vendor Updates 080221

application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generate_po.php
1. Change to ID for fetching datas
=> Generate PO Updates:080321

application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generate_po.php, application/views/P.O/generated_po_edit.php, application/views/P.O/script.php
P.O Updates: 080521
1. Edit Form for Generated P.O - DONE
2. PO order no. Revision code - DONE
=> PO Updates: 080521

application/models/JobOrderModel.php
1. for Phone Support Status display
=> JO-Updates: 080621

application/controllers/JobOrderController.php, application/views/job_order/script.php
1. Discard button form error - DONE
=> JO Updates: 090821

application/controllers/POController.php
1. Remove Edit Button for Generated PO
=> PO Updates: 090821

application/controllers/RequisitionFormController.php, application/models/RequisitionFormModel.php, application/views/requisition_form/requisition_form.php, application/views/requisition_form/script.php
1. supplier drop down list ascending order - DONE
2. pending requisition view of items supplier name(as of now supplier ID displayed) - DONE
3. amount coma for 5 digit - DONE
4. Approved button in edit form for pending requisitions - DONE
5. remove function of approved requisition(if fill up approved by sir nino) in submit button - DONE
=> Requisition Updates:090821

application/controllers/RequisitionFormController.php, application/views/requisition_form/requisition_view.php
1. Filed Requisitions Supplier Display in print
=> Requisition Updates: 081421

application/config/routes.php, application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generated_po_list.php, application/views/P.O/script.php, application/views/templates/navbar.php
1. Pending PO Tab - DONE
2. Accepted PO tab - DONE
3. Approved Po Validation - DONE
4. Approved and Pending PO Table List - DONE
=> PO Udpates: 081821

application/controllers/LoginController.php, application/controllers/POController.php, application/models/POModel.php
1. PO Bug due to PO generating when supplier is null - FIXED
2. PO generation not merging per supplier - FIXED
=> PO-Updates: 082321

application/config/routes.php, application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generate_po.php
1. Generation of PO Bug due to blank supplier generates PO in database - FIXED
2. PO Generation of items due to selected items only - DONE
3. PO Generation Bug due to supplier items not merged - FIXED
4. PO Bug due to po generating when supplier is null - FIXED
5. PO generation not merging per supplier - FIXED
6. Generated PO Supplier Acronym Display - FIXED
=> PO Updates: 082521

application/config/config.php, application/controllers/VendorController.php, application/views/P.O/generate_po.php, application/views/vendor/vendor_add.php, application/views/vendor/vendor_edit.php
1. add vendor terms: 21days
2. display of vendor terms in print preview
=> vendor database, generated PO updates 100121

application/controllers/VendorController.php, application/views/vendor/vendor_add.php, application/views/vendor/vendor_datatable.php, application/views/vendor/vendor_edit.php
1. Bank Name - done
2. Account Name - done
3. Account Number - done
=> Vendor Database Updates: 100521

application/controllers/POController.php, application/models/POModel.php
1.  generated PO bug of items still adding to recent generated po for supplier
=> generate-po-updates-101521

application/controllers/VendorController.php
1. opening database error occured(vendor 57 error data) - need to edit info by mam V
2. set required validation for supplier ranking - DONE
=> Vendor Database Updates:103121

application/controllers/CustomersController.php, application/models/CustomersModel.php, application/views/customers/customers_table.php, application/views/customers/script.php
1. delete button not working - DONE
2. add projects list(100%) for refference only - DONE
=> Customer List Updates: 102921

application/controllers/CustomersController.php, application/controllers/SalesInquiryController.php, application/views/sales_inquiry/existing_client_view.php, application/views/sales_inquiry/new_client_view.php, application/views/sales_inquiry/project_view.php, application/views/sales_inquiry/script.php
1. change of installation date to added date in new clients data - DONE
2. add installation date in projects data - DONE
3. projects branch status validation - revised and debug
4. add branch contact personnel - DONE
5. add branch contact number - DONE
6. new client added column validation - done
7. new client added column validation - done
=> Sales Inquiry Updates: 110121

application/config/routes.php, application/controllers/PayrollController.php, application/models/PayrollModel.php, application/views/payroll/payroll_table.php, application/views/templates/header.php
1. Conversion of payroll cutoff to csv file - DONE
2. button for exporting csv file - DONE
=> Payroll Updates: 112421

application/controllers/DispatchFormController.php, application/models/DispatchFormsModel.php, application/views/Forms/Dispatch.php, application/views/Forms/DispatchTable.php, application/views/Forms/script.php
1. Add Back Job in Type of Service Field - DONE(011322)
2. Display of New Data(Back Job)
=> Dispatch Form Updates: 011322

application/controllers/LeaveController.php, application/views/leave/print_filed_leave.php
1. Relocate of qr_image location - DONE
2. revise of adding and displaying of qr_image to codes - DONE
=> AFLA Updates: 011522

application/views/Forms/printdispatch.php
1. Back Job no display in dispatch print form - DONE(020222)
=> Dispatch Form Updates: 012622

application/views/P.O/generate_po.php
1. Replace sir vin name to sir nino - DONE(020222)
2. Replace recommending approval by prepared by - DONE(020222)
=>  PO Updates: 010522

application/controllers/TechniciansController.php, application/views/technicians/technicians_add.php, application/views/technicians/technicians_edit.php
1. add new status(managerial) - DONE(020222)
2. Employee list accces restriction - DONE(020222)
=> Employee List Updates:121721

application/controllers/JobOrderController.php, application/models/JobOrderModel.php, application/views/job_order/job_order.php
1. add WAP, video wall in scope - DONE(020222)
=> JO updates: 112521

application/controllers/RequisitionFormController.php
1. Remove Edit and Discard button in Approved List - DONE(020222)
=> Requisition Form UPDATES: 013122

application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generate_po.php, application/views/P.O/generated_po_list.php, application/views/P.O/script.php
1. add Filed List - DONE(020222)
=> PO Updates:

application/views/P.O/generated_po_list.php
1. Approved PO Validation error - FXED
=> PO-Updates: 020322

application/views/PRF/prf_form.php
1. Hotfix of items system stock display
=> PRF Hotfix: 020422

application/controllers/RequisitionFormController.php, application/views/requisition_form/requisition_form.php, application/views/requisition_form/requisition_list.php, application/views/requisition_form/script.php
1. required processed, received & checked by field in pending request - DONE(020922)
=> Requisition Form Updates:012922

application/controllers/RequisitionFormController.php, application/views/requisition_form/requisition_list.php, application/views/requisition_form/script.php
1. Add requisition ID Display in items view list - DONE(022422)
=> Requisition Form Updates: 022422

application/views/Forms/printdispatch.php, application/views/P.O/generate_po.php
1. change of logo in dispatch
2. change of text from vinculum tech enterprise to vinculum technologies corporation
=> PO & dispatch prints updates-030222

application/views/dashboard/dashboard.php, application/views/schedules/schedules.php, application/views/schedules/script.php
1. Add Deployment in Legends - DONE(022622:234p)
2. Add Project Turnover in Legends - ONE(020322:1145a)
=> Schedules Form Updates: 022622

application/config/routes.php, application/controllers/POController.php, application/models/POModel.php, application/views/P.O/generate_po.php, application/views/P.O/generated_po_list.php, application/views/P.O/script.php, application/views/requisition_form/requisition_form.php, application/views/templates/footer.php
1. Generate Reports for supplier, project & date range - Almost DONE(03052)
2. need to add final items printed - DONE(030922)
=> PO Form Updates: 030222

application/controllers/VendorController.php, application/views/vendor/vendor_add.php, application/views/vendor/vendor_edit.php
1. Add 3 & 5 Days in terms field - DONE(031222)
2. Add 3 & 5 Days in Display fields - DONE(031222)
=> Vendor Updates: 031222

application/views/P.O/generate_po.php
1. Display of terms in print form - DONE(031222)
=> PO Updates: 031222

application/models/ItemsModel.php, application/models/ToolsModel.php
1. Generate Excel file for Direct, Indirect and tools list where stock is not 0 - DONE(032822)
=> Items Masterlist Updates: 032822

application/config/routes.php, application/controllers/ToolsController.php, application/models/ToolsModel.php, application/views/tools/tools.php
1. Export Data for all tools(on stock & pulled-out items) - DONE(032922)
=> Tools Updates: 032922

application/models/ItemsModel.php
1. export all items(Direct & Indirect)
=> Items Masterlist Updates: 040122

application/controllers/JobOrderController.php, application/models/JobOrderModel.php, application/views/job_order/job_order.php, application/views/job_order/script.php
1. Add 2 New PIC in PIC Field List, Datatable display, edit form - DONE(040522)
=> JO-List-Updates: 040522

application/config/routes.php, application/controllers/VendorController.php, application/models/VendorModel.php, application/views/vendor/vendor_datatable.php
1. exporting of vendors database to excel file
=> vendor updates: 042522
